---
- name: Validate input.yml syntax and structure
  block:

    - name: Test YAML syntax of input.yml
      include_vars:
        file: "input.yml"
        name: test_input
      register: yaml_syntax_check
      ignore_errors: yes

    - name: Fail if YAML syntax is invalid
      fail:
        msg: "ERROR: Invalid YAML syntax in input.yml - {{ yaml_syntax_check.msg | default('Unknown syntax error') }}"
      when: yaml_syntax_check is failed


    - name: Validate VMs array is not empty
      fail:
        msg: "ERROR: 'vms' array is empty in input.yml"
      when: test_input.vms | length == 0

    - name: Validate each VM has at least 3 network interfaces
      fail:
        msg: "ERROR: VM '{{ vm_item.name | default('unnamed') }}' must have at least 3 network interfaces, but has {{ vm_item.networkInterface | length }}"
      when:
        - vm_item.networkInterface is defined
        - vm_item.networkInterface | length < 3
        - '"F5" in vm_item.vm_type'

      loop: "{{ test_input.vms }}"
      loop_control:
        loop_var: vm_item

    - name: Validate individual VM configurations
      fail:
        msg: "ERROR: VM '{{ vm_item.name | default('unnamed') }}' is missing required field '{{ required_field }}'"
      when: 
       - '"F5" in vm_item.vm_type' 
       - vm_item[required_field] is not defined
      
      loop: "{{ test_input.vms | product(['name', 'vm_type', 'hostip', 'networkInterface', 'vm_resource','f5_config']) | list }}"
      loop_control:
        loop_var: vm_field_pair
      vars:
        vm_item: "{{ vm_field_pair[0] }}"
        required_field: "{{ vm_field_pair[1] }}"

    - name: Display input validation success
      debug:
        msg: "Input validation passed successfully"

  rescue:
    - name: Display validation error and stop execution
      fail:
        msg: "Input validation failed. Please fix the errors in input.yml and try again."

