---
- hosts: localhost
  gather_facts: no
  vars:
    vms_to_create: []
    already_present: [] # Assumes check_vmpresent.yml appends to this list

  tasks:

    - name: Check which VMs are already present on the hypervisors
      # We now loop over the WRAPPER file.
      ansible.builtin.include_tasks: wrapper_check_vmpresent.yml
      loop: "{{ vms }}"
      loop_control:
        loop_var: item

    - name: Finalize list of VMs that need to be created
      ansible.builtin.set_fact:
        vms_to_create: "{{ vms_to_create + [item] }}"
      loop: "{{ vms }}"
      loop_control:
        loop_var: item
      when: item.name not in (already_present | default([]))

    - name: Announce which VMs will be created
      ansible.builtin.debug:
        var: vms_to_create

    - name: Set workflow facts for the next job
      ansible.builtin.set_stats:
        data:
          vms_to_create: "{{ vms_to_create }}"
          effective_setup: "{{ setup | default(0) }}"
