---
- hosts: all
  gather_facts: no
  vars:
    vms_to_create: []
    already_present: []

  tasks:

    - name: Check which VMs are already present
      ansible.builtin.include_tasks: wrapper_check_vmpresent.yml
      loop: "{{ vms }}"
      loop_control:
        loop_var: item

    # ADD THIS DEBUG TASK
    - name: DEBUG | Show the final structure of vms_to_create
      ansible.builtin.debug:
        var: vms_to_create

    - name: Finalize list of VMs to create
      ansible.builtin.set_fact:
        vms_to_create: "{{ vms_to_create + [item] }}"
      loop: "{{ vms }}"
      loop_control:
        loop_var: item
      when: item.name not in (already_present | default([]))

    - name: Set workflow facts for the next job
      ansible.builtin.set_stats:
        data:
          vms_to_create: "{{ vms_to_create }}"
          effective_setup: "{{ setup | default(0) }}"
          vmimage: "{{ vmimage }}"
          vg_name: "{{ vg_name }}"
