# 1_preflight_checks.yml
---
- hosts: all
  gather_facts: no

  #
  # The 'vars_files' section is now removed.
  # The playbook will use the variables provided by the AAP Job Template.
  #
  vars:
    configured_vms: []
    already_present: []
    configured_vms_path: /usr/local/bin/vmautomation-playbook/configured_vms.txt

  tasks:
    - name: Validate input for each VM
      # This task was correct, no changes needed here if it works
      ansible.builtin.include_tasks: files/validate_input.yml
      loop: "{{ vms }}"
      loop_control:
        loop_var: item

    - name: Check for existing VMs and build creation list
      # We loop over the WRAPPER file, not a block.
      ansible.builtin.include_tasks: wrapper_check_vmpresent.yml
      loop: "{{ vms }}"
      loop_control:
        loop_var: item

    - name: Finalize list of VMs to create
      ansible.builtin.set_fact:
        vms_to_create: "{{ vms_to_create + [item] }}"
      loop: "{{ vms }}"
      loop_control:
        loop_var: item
      when: item.name not in (already_present | default([]))

    - name: Announce which VMs will be created
      ansible.builtin.debug:
        var: vms_to_create

    - name: Set workflow facts for VMs to be created
      ansible.builtin.set_stats:
        data:
          vms_to_create: "{{ vms_to_create }}"
