# 2_generate_and_launch.yml
---
- hosts: localhost
  gather_facts: no
  vars:
    vms_to_create: []
    successful_vms: [] # Initialize the list here

  tasks:
    - name: Generate configurations and launch VMs
      # This include_tasks will loop, running the wrapper file for each VM
      ansible.builtin.include_tasks: tasks_generate_and_launch_single_vm.yml
      loop: "{{ vms_to_create }}"
      loop_control:
        loop_var: item

    - name: Set workflow facts for launched VMs
      ansible.builtin.set_stats:
        data:
          launched_vms: "{{ successful_vms | default([]) }}"
