---
- name: Launch multiple VMs in parallel
  hosts: all
  gather_facts: no
  vars:
    successful_vms: []
    failed_vms: []
    vm_state: {}

  tasks:
    - name: "Launch all new VMs"
      ansible.builtin.include_tasks: launch_vm_task.yml
      loop: "{{ vms_to_create | from_yaml }}"
      loop_control:
        loop_var: vm_item

    - name: "Final report of failed VMs"
      ansible.builtin.debug:
        msg: "❌ Failed VMs: {{ failed_vms | default([]) }}"

    - name: "Set workflow facts for the next job"
      ansible.builtin.set_stats:
        data:
          launched_vms: "{{ successful_vms }}"

