- hosts: localhost
  gather_facts: no
  vars:
    successful_vms: []
  tasks:
    - name: Launch all new VMs
      ansible.builtin.include_tasks: wrapper_launch_vm.yml
      loop: "{{ vms_to_create | from_yaml }}"
      loop_control:
        loop_var: item

    - name: Set workflow facts for the next job
      ansible.builtin.set_stats:
        data:
          launched_vms: "{{ successful_vms }}"

