# 3_post_configure.yml
---
- hosts: localhost
  gather_facts: no
  vars:
    # This list is passed from the previous workflow step
    launched_vms: []
    failed_vms: []

  tasks:
    - name: Wait for VM launch jobs to complete
      ansible.builtin.async_status:
        jid: "{{ item.job_id }}"
      register: job_result
      until: job_result.finished
      retries: 60 # Retry for 30 minutes (60 * 30s delay)
      delay: 30
      loop: "{{ launched_vms }}"
      loop_control:
        loop_var: item
      delegate_to: "{{ item.hostip }}"
      failed_when: job_result.rc != 0
      ignore_errors: true

    - name: Collect failed VMs
      ansible.builtin.set_fact:
        failed_vms: "{{ failed_vms + [item.name] }}"
      when: job_result.rc != 0
      loop: "{{ launched_vms }}"
      loop_control:
        loop_var: item

    # --- Dynamic Inventory Setup ---
    - name: Create an in-memory inventory group for new VMs
      ansible.builtin.add_host:
        name: "{{ item.vm_vars.networkInterface[0].ipaddress | ipaddr('address') }}"
        groups: new_vms
        # Pass all necessary vars for the next play
        ansible_user: "{{ user }}"
        ansible_password: "{{ password }}"
        vm_name: "{{ item.name }}"
        vm_type: "{{ item.vm_vars.vm_type }}"
      loop: "{{ launched_vms }}"
      loop_control:
        loop_var: item
      when: item.name not in failed_vms

# --- New Play targeting the newly created VMs ---
- hosts: new_vms
  gather_facts: no

  tasks:
    - name: Wait for SSH to be available
      ansible.builtin.wait_for_connection:
        delay: 20
        timeout: 300

    - name: Run Post VM Configuration
      ansible.builtin.include_tasks: files/PostVMLaunch.yml
      # Vars like vm_name and vm_type were passed via add_host

    - name: Fail if any VMs failed to launch
      ansible.builtin.fail:
        msg: "The following VMs failed to launch or configure: {{ hostvars['localhost']['failed_vms'] }}"
      run_once: true
      when: (hostvars['localhost']['failed_vms'] | default([])) | length > 0
