---
# launch_vm_task.yml
- name: "Launching VM {{ vm_item.name }}"
  ansible.builtin.shell: >
    sudo bash -x /usr/local/bin/vm_build_and_install.sh
    -d 4 -v RESTORE {{ vm_item.name }}
  async: 7200        # run up to 2 hours in background
  poll: 0            # don’t wait, run in background
  delegate_to: "{{ vm_item.hostip }}"
  register: vm_async_job
  ignore_errors: true

- name: "Track async job for {{ vm_item.name }}"
  ansible.builtin.set_fact:
    async_jobs: "{{ async_jobs | default([]) + [ { 'name': vm_item.name, 'job_id': vm_async_job.ansible_job_id, 'host': vm_item.hostip } ] }}"

