---
- name: Multi-VM Deployment
  hosts: all
  gather_facts: false
  vars:
    vm_list: []
    failed_vms: []

  tasks:

    - name: Create VMs
      include_role:
        name: create_vm
      vars:
        vm: "{{ item }}"
      loop: "{{ vm_list }}"
      loop_control:
        loop_var: item
      ignore_errors: yes
      register: create_results

    - name: Configure VMs
      include_role:
        name: configure_vm
      vars:
        vm: "{{ item }}"
      loop: "{{ vm_list }}"
      loop_control:
        loop_var: item
      ignore_errors: yes
      register: configure_results

    - name: Harden VMs (optional)
      include_role:
        name: harden_vm
      vars:
        vm: "{{ item }}"
      loop: "{{ vm_list }}"
      loop_control:
        loop_var: item
      ignore_errors: yes
      when: item.harden | default(false)
      register: harden_results

    - name: Collect failed VMs
      set_fact:
        failed_vms: >-
          {{ create_results.results
             | selectattr('failed','defined')
             | selectattr('failed')
             | map(attribute='item.name')
             | list +
             configure_results.results
             | selectattr('failed','defined')
             | selectattr('failed')
             | map(attribute='item.name')
             | list +
             harden_results.results
             | selectattr('failed','defined')
             | selectattr('failed')
             | map(attribute='item.name')
             | list
          }}

    - name: Report failed VMs
      debug:
        msg: "The following VMs failed: {{ failed_vms }}"

