---
- name: "Generate configs and launch VM: {{ item.name }}"
  block:
    - name: Include create_cfg role
      ansible.builtin.include_role:
        name: create_cfg
      vars:
        vm_name: "{{ item.name }}"
        vm_type: "{{ item.vm_type }}"
        # item: "{{ item }}"  <-- REMOVED THIS LINE

    - name: Include create_ini role
      ansible.builtin.include_role:
        name: create_ini
      vars:
        vm_name: "{{ item.name }}"
        vm_type: "{{ item.vm_type }}"
        # item: "{{ item }}"  <-- REMOVED THIS LINE

    - name: Include create_vm role to launch VM and get Job ID
      ansible.builtin.include_role:
        name: create_vm
      vars:
        vm_name: "{{ item.name }}"
        vm_type: "{{ item.vm_type }}"
        # item: "{{ item }}"  <-- REMOVED THIS LINE
      register: create_vm_role_result

    - name: Store successful launch job ID
      ansible.builtin.set_fact:
        successful_vms: "{{ successful_vms | default([]) + [{'name': item.name, 'job_id': create_vm_role_result.ansible_facts.create_vm_job_id, 'hostip': item.hostip, 'vm_vars': item }] }}"

  delegate_to: "{{ item.hostip }}"
