---
# This file contains the tasks for generating configs and launching a SINGLE VM.
# It is called by the main playbook inside a loop.

- name: "Process VM: {{ item.name }}"
  block:
    - name: Include create_cfg role
      ansible.builtin.include_role:
        name: create_cfg
      vars:
        # Pass necessary variables to the role
        vm_name: "{{ item.name }}"
        vm_type: "{{ item.vm_type }}"
        effective_setup: "{{ effective_setup | default(0) }}"

    - name: Include create_ini role
      ansible.builtin.include_role:
        name: create_ini
      vars:
        vm_name: "{{ item.name }}"
        vm_type: "{{ item.vm_type }}"

    - name: Include create_vm role to launch VM and get Job ID
      ansible.builtin.include_role:
        name: create_vm
      vars:
        vm_name: "{{ item.name }}"
        vm_type: "{{ item.vm_type }}"
      register: create_vm_role_result

    - name: Store successful launch job ID
      ansible.builtin.set_fact:
        successful_vms: "{{ successful_vms | default([]) + [{'name': item.name, 'job_id': create_vm_role_result.ansible_facts.create_vm_job_id, 'hostip': item.hostip, 'vm_vars': item }] }}"

  # The delegate_to is correctly placed on the block, applying to all tasks inside
  delegate_to: "{{ item.hostip }}"
