---
# wait_vm_async.yml
# Wait for async VM job to finish and track success/failure

- name: "Check async job status for {{ item.name }}"
  ansible.builtin.async_status:
    jid: "{{ item.job_id }}"
  register: job_result
  until: job_result.finished
  retries: 60
  delay: 30
  failed_when: job_result.rc != 0

- name: "Add VM to success list"
  set_fact:
    successful_vms: "{{ successful_vms | default([]) + [item] }}"
  when: job_result.finished and job_result.rc == 0

- name: "Add VM to failure list if job failed"
  set_fact:
    failed_vms: "{{ failed_vms | default([]) + [item] }}"
  when: job_result.finished and job_result.rc != 0

