---
- name: "Launch multiple VMs in parallel"
  hosts: localhost
  gather_facts: no
  tasks:
    # This task runs the SAME role for multiple VMs at once
    - name: "Start create_vm role for {{ item.name }} on {{ item.hostip }}"
      ansible.builtin.include_role:
        name: create_vm
      vars:
        vm_name: "{{ item.name }}"
        vm_info: "{{ item }}"
      delegate_to: "{{ item.hostip }}"
      async: 3600
      poll: 0  # This keyword is what makes it parallel
      loop: "{{ vm_list }}"
      register: vm_creation_jobs

    # This task waits for all the parallel jobs to finish
    - name: "Wait for all VM creation jobs to finish"
      ansible.builtin.async_status:
        jid: "{{ item.ansible_job_id }}"
      loop: "{{ vm_creation_jobs.results }}"
      register: job_result
      until: job_result.finished
      retries: 120
      delay: 30
      loop_control:
        label: "{{ item.item.name }}"
