---
- name: "Launch multiple VMs asynchronously (wrapper)"
  hosts: localhost
  gather_facts: no
  vars:
    successful_vms: []
    failed_vms: []
    launched_vms: []
  tasks:

    - name: "Launch all VMs asynchronously using create_vm role"
      ansible.builtin.include_role:
        name: create_vm
      vars:
        vm_name: "{{ vm_item.name }}"
        vm_info: "{{ vm_item }}"
      register: vm_launch_results
      loop: "{{ vm_list }}"
      loop_control:
        loop_var: vm_item

    - name: "Store async job details for all launched VMs"
      ansible.builtin.set_fact:
        launched_vms: >-
          {%- set vms = [] -%}
          {%- for r in vm_launch_results.results -%}
            {%- set _ = vms.append({
                  'name': r.item.name,
                  'hostip': r.item.hostip,
                  'job_id': r.ansible_facts.create_vm_job_id
            }) -%}
          {%- endfor -%}
          {{ vms }}

    - name: "Debug: list of launched VM async jobs"
      ansible.builtin.debug:
        msg: "{{ launched_vms }}"

    - name: "Wait for all VM async jobs to complete"
      ansible.builtin.async_status:
        jid: "{{ item.job_id }}"
      register: job_result
      until: job_result.finished
      retries: 60
      delay: 30
      failed_when: job_result.rc != 0
      loop: "{{ launched_vms }}"
      loop_control:
        loop_var: item

    - name: "Debug: Final launched VM status"
      ansible.builtin.debug:
        msg:
          launched: "{{ launched_vms }}"

