---
- name: "Delegate launch for {{ vm_item.name }}"
  block:
    - name: Include create_vm role
      ansible.builtin.include_role:
        name: create_vm
      vars:
        vm_name: "{{ vm_item.name }}"
      register: create_vm_role_result

    - name: Store successful launch job ID and VM data
      ansible.builtin.set_fact:
        successful_vms: "{{ successful_vms | default([]) + [{'name': vm_item.name, 'ip_address': vm_item.networkInterface[0].ipaddress | ipaddr('address'), 'job_id': create_vm_role_result.ansible_facts.create_vm_job_id, 'hostip': vm_item.hostip}] }}"
  delegate_to: "{{ vm_item.hostip }}"

