---
- name: "Delegate launch for {{ vm_item.name }}"
  block:
    - name: Include create_vm role
      ansible.builtin.include_role:
        name: create_vm
      vars:
        vm_name: "{{ vm_item.name }}"
        vm_info: "{{ vm_item }}"
      register: create_vm_role_result

  delegate_to: "{{ vm_item.hostip }}"

