---
- name: "Wait for async job {{ current_vm.name }} to finish"
  ansible.builtin.async_status:
    jid: "{{ current_vm.job_id }}"
  register: job_result
  until: job_result.finished
  retries: 60
  delay: 30
  failed_when: job_result.rc != 0

- name: "Add VM {{ current_vm.name }} to success list"
  ansible.builtin.set_fact:
    successful_vms: "{{ successful_vms | default([]) + [current_vm] }}"
  when: job_result.finished

- name: "Add VM {{ current_vm.name }} to failure list if async job failed"
  ansible.builtin.set_fact:
    failed_vms: "{{ failed_vms | default([]) + [current_vm] }}"
  when: job_result.finished is not defined or job_result.rc != 0

