---
# Check async job status for a single VM
- name: "Check async job status for {{ item.name }}"
  ansible.builtin.async_status:
    jid: "{{ item.job_id }}"
  register: job_result
  until: job_result.finished
  retries: 60
  delay: 30
  failed_when: job_result.rc != 0

- name: "Add VM {{ item.name }} to success list"
  ansible.builtin.set_fact:
    successful_vms: "{{ successful_vms | default([]) + [item] }}"
  when: job_result.finished

- name: "Add VM {{ item.name }} to failure list if job failed"
  ansible.builtin.set_fact:
    failed_vms: "{{ failed_vms | default([]) + [item] }}"
  when: not job_result.finished

