---
# check_vm_present.yml
- name: Check if VM {{ item.name }} is already configured
  become: yes
  shell: grep -w "{{ item.name }}" "{{configured_vms_path}}"
  ignore_errors: true
  register: vm_present

- name: VM's already Configured
  set_fact:
    configured_vms: "{{ configured_vms | default([]) + [item.name] }}"
  when: item.name in vm_present.stdout


- name: Debug configured VMs
  debug:
    msg: "{{ configured_vms }}"