# worker.yml
- name: Provision a Single VM
  hosts: all # Job runs on a controller node; tasks are delegated
  gather_facts: no
  # 'vm_details', 'user', 'password', and 'setup' are passed in as extra_vars

  vars:
    # Set local variables from the passed-in dictionary for easier access
    vm_type: "{{ vm_details.vm_type }}"
    vm_name: "{{ vm_details.name }}"
    host_ip: "{{ vm_details.hostip }}"
    is_present: false # Default state

  tasks:
    - name: "INFO: Processing VM '{{ vm_name }}' on host '{{ host_ip }}'"
      debug:
        msg: "Setup Type is {{ 'On-Prem' if setup == '0' else 'Wavelite' }}"

    # --- Pre-check Block ---
    - name: Check if VM is already present or configured
      block:
        - name: Check vm is present
          include_tasks: files/check_vmpresent.yml
          delegate_to: "{{ host_ip }}"
          vars:
            item: "{{ vm_details }}"
          register: check_present_result

        - name: Set presence fact if VM is already present
          set_fact:
            is_present: true
          # NOTE: This condition depends on the output of 'check_vmpresent.yml'.
          # You may need to adjust it based on the actual success message.
          when: "'already present' in check_present_result.msg | default('')"

        - name: Check vm is configured (non-F5)
          include_tasks: files/check_vmconfigured.yml
          delegate_to: "{{ host_ip }}"
          when: "'F5' not in vm_type and not is_present"
          vars:
            item: "{{ vm_details }}"
      # The original playbook implies that pre-checks should not stop the entire run
      ignore_errors: true

    # --- Provisioning Block ---
    - name: Provision the VM if it is not already present
      block:
        - name: Validate input for F5 VMs
          include_tasks: files/validate_input.yml
          delegate_to: localhost
          when: "'F5' in vm_type"
          vars:
            item: "{{ vm_details }}"

        - name: Generate Cfg (non-F5)
          include_role:
            name: create_cfg
          delegate_to: "{{ host_ip }}"
          when: "'F5' not in vm_type"
          vars:
            vm_type: "{{ vm_type }}"
            vm_name: "{{ vm_name }}"

        - name: Generate Ini
          include_role:
            name: create_ini
          delegate_to: "{{ host_ip }}"
          vars:
            vm_type: "{{ vm_type }}"
            vm_name: "{{ vm_name }}"

        - name: Launch VM
          include_role:
            name: create_vm
          delegate_to: "{{ host_ip }}"
          vars:
            vm_type: "{{ vm_type }}"
            vm_name: "{{ vm_name }}"

        - name: Wait 5 minutes for VM initialization
          wait_for:
            timeout: 300
          delegate_to: localhost

        - name: Post VM Configuration (non-F5)
          include_tasks: files/PostVMLaunch.yml
          when: "'F5' not in vm_type"
          vars:
            vm: "{{ vm_details }}"
            ansible_user: "{{ user }}"
            ansible_password: "{{ password }}"

      when: not is_present

    - name: "SKIP: VM {{ vm_name }} was already present."
      debug:
        msg: "VM {{ vm_name }} was already present. No action taken."
      when: is_present

